name: Tasks TMX Moon runner
on: [push]
jobs:
  TMX-Moon:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "18", "20"]
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: yarn run lint
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: Docker containerization
        run: docker compose up -d
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
